"""Cria estrutura inicial de tabelas

Revision ID: 41fb54bbe0b1
Revises: 
Create Date: 2025-10-06 12:11:41.717570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41fb54bbe0b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vagas',
    sa.Column('id_vaga', sa.Integer(), nullable=False),
    sa.Column('portal', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('descricao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_coleta', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_vaga'),
    sa.UniqueConstraint('url')
    )
    op.create_table('vocabulario',
    sa.Column('id_palavra', sa.Integer(), nullable=False),
    sa.Column('palavra', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_palavra'),
    sa.UniqueConstraint('palavra')
    )
    op.create_table('vaga_tfidf',
    sa.Column('id_vaga', sa.Integer(), nullable=False),
    sa.Column('id_palavra', sa.Integer(), nullable=False),
    sa.Column('score_tfidf', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_palavra'], ['vocabulario.id_palavra'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_vaga'], ['vagas.id_vaga'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_vaga', 'id_palavra')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaga_tfidf')
    op.drop_table('vocabulario')
    op.drop_table('vagas')
    # ### end Alembic commands ###
